services:
  mysql:
    container_name: eco-rich-homework-mysql
    image: mysql:8.4.3
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=hr
    ports:
      - "3306:3306"
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci' ]